import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import type { Visual, BrandJson } from "../llm/schemas.js";
import type { LogoResult } from "../generate/logo.js";

export async function writeAssets(
  root: string,
  brand: BrandJson,
  logo?: LogoResult,
  ogImage?: Buffer
): Promise<string[]> {
  const assetsDir = join(root, ".gesso");
  await mkdir(assetsDir, { recursive: true });

  const written: string[] = [];

  // CSS custom properties
  const css = generateCssTokens(brand.visual);
  const cssPath = join(assetsDir, "brand-tokens.css");
  await writeFile(cssPath, css, "utf-8");
  written.push(cssPath);

  // Tailwind config snippet
  const tw = generateTailwindConfig(brand.visual);
  const twPath = join(assetsDir, "tailwind-brand.js");
  await writeFile(twPath, tw, "utf-8");
  written.push(twPath);

  // Logo SVGs (light + dark variants)
  if (logo) {
    const lightPath = join(assetsDir, "logo-light.svg");
    await writeFile(lightPath, logo.light, "utf-8");
    written.push(lightPath);

    const darkPath = join(assetsDir, "logo-dark.svg");
    await writeFile(darkPath, logo.dark, "utf-8");
    written.push(darkPath);
  }

  // OG image
  if (ogImage) {
    const ogPath = join(assetsDir, "og-image.png");
    await writeFile(ogPath, ogImage);
    written.push(ogPath);
  }

  return written;
}

function generateCssTokens(visual: Visual): string {
  return `:root {
  /* ${visual.paletteName} — generated by gesso */
  --brand-primary: ${visual.palette.primary};
  --brand-secondary: ${visual.palette.secondary};
  --brand-accent: ${visual.palette.accent};
  --brand-background: ${visual.palette.background};
  --brand-text: ${visual.palette.text};
  --brand-muted: ${visual.palette.muted};

  --font-heading: '${visual.fontPairing.heading}', system-ui, sans-serif;
  --font-body: '${visual.fontPairing.body}', system-ui, sans-serif;
}
`;
}

function generateTailwindConfig(visual: Visual): string {
  return `// Brand tokens — generated by gesso
// Add to your tailwind.config.js: theme.extend.colors and theme.extend.fontFamily

export const brandColors = {
  primary: "${visual.palette.primary}",
  secondary: "${visual.palette.secondary}",
  accent: "${visual.palette.accent}",
  background: "${visual.palette.background}",
  text: "${visual.palette.text}",
  muted: "${visual.palette.muted}",
};

export const brandFonts = {
  heading: ["${visual.fontPairing.heading}", "system-ui", "sans-serif"],
  body: ["${visual.fontPairing.body}", "system-ui", "sans-serif"],
};
`;
}
