import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { BrandJson } from "../llm/schemas.js";

export function renderBrandMd(brand: BrandJson): string {
  const lines: string[] = [];

  lines.push(`# ${brand.productName} Brand Guide`);
  lines.push("");
  lines.push(`> Generated by [gesso](https://github.com/gsymmy30/gesso) on ${new Date().toLocaleDateString()}`);
  lines.push("");

  // Positioning
  lines.push("## Positioning");
  lines.push("");
  lines.push(`**One-liner:** ${brand.positioning.oneLiner}`);
  lines.push("");
  lines.push(`**Tagline:** ${brand.positioning.tagline}`);
  lines.push("");
  lines.push(`**Positioning statement:** ${brand.positioning.positioningStatement}`);
  lines.push("");
  lines.push(`**Category:** ${brand.positioning.category}`);
  lines.push("");
  lines.push("### Elevator Pitch");
  lines.push("");
  lines.push(brand.positioning.elevatorPitch);
  lines.push("");

  // Voice
  lines.push("## Voice & Tone");
  lines.push("");
  lines.push(`**Personality:** ${brand.voice.personality}`);
  lines.push("");
  lines.push(`**Tone words:** ${brand.voice.toneWords.join(", ")}`);
  lines.push("");
  lines.push("### Do");
  lines.push("");
  for (const item of brand.voice.doList) {
    lines.push(`- ${item}`);
  }
  lines.push("");
  lines.push("### Don't");
  lines.push("");
  for (const item of brand.voice.dontList) {
    lines.push(`- ${item}`);
  }
  lines.push("");
  lines.push("### Example Sentences");
  lines.push("");
  for (const sentence of brand.voice.exampleSentences) {
    lines.push(`> ${sentence}`);
    lines.push("");
  }
  lines.push("### Banned Words");
  lines.push("");
  lines.push(brand.voice.bannedWords.join(", "));
  lines.push("");

  // Copy
  lines.push("## Copy");
  lines.push("");
  lines.push(`**Hero headline:** ${brand.copy.heroHeadline}`);
  lines.push("");
  lines.push(`**Hero subheadline:** ${brand.copy.heroSubheadline}`);
  lines.push("");
  lines.push(`**OG description:** ${brand.copy.ogDescription}`);
  lines.push("");
  lines.push("### README Intro");
  lines.push("");
  lines.push(brand.copy.readmeIntro);
  lines.push("");
  lines.push("### Launch Tweet");
  lines.push("");
  lines.push(`> ${brand.copy.tweetLaunch}`);
  lines.push("");
  lines.push("### Launch Post");
  lines.push("");
  lines.push(brand.copy.launchPost);
  lines.push("");

  // Visual
  lines.push("## Visual Identity");
  lines.push("");
  lines.push(`**Palette:** ${brand.visual.paletteName}`);
  lines.push("");
  lines.push("| Role | Color |");
  lines.push("|------|-------|");
  for (const [role, color] of Object.entries(brand.visual.palette)) {
    lines.push(`| ${role} | \`${color}\` |`);
  }
  lines.push("");
  lines.push(`**Fonts:** ${brand.visual.fontPairing.heading} (headings) / ${brand.visual.fontPairing.body} (body)`);
  lines.push("");

  // SEO
  lines.push("## SEO");
  lines.push("");
  lines.push(`**Meta title:** ${brand.seo.metaTitle}`);
  lines.push("");
  lines.push(`**Meta description:** ${brand.seo.metaDescription}`);
  lines.push("");
  lines.push(`**Keywords:** ${brand.seo.keywords.join(", ")}`);
  lines.push("");

  return lines.join("\n");
}

export async function writeBrandMd(
  root: string,
  brand: BrandJson
): Promise<string> {
  const content = renderBrandMd(brand);
  const filePath = join(root, "brand.md");
  await writeFile(filePath, content + "\n", "utf-8");
  return filePath;
}
