// Brand tokens — generated by gesso
// Add to your tailwind.config.js: theme.extend.colors and theme.extend.fontFamily

export const brandColors = {
  primary: "#2D3748",
  secondary: "#4A5568",
  accent: "#ED8936",
  background: "#FAFAFA",
  text: "#1A202C",
  muted: "#718096",
};

export const brandFonts = {
  heading: ["JetBrains Mono", "system-ui", "sans-serif"],
  body: ["Inter", "system-ui", "sans-serif"],
};
